export const runnerFacts = [
  "Le record du monde du marathon : 2h00min35s par Kelvin Kiptum !",
  "Usain Bolt atteignait 44.72 km/h en pointe sur 100m.",
  "Un marathonien elite fait environ 43 000 pas pendant une course.",
  "Le trail le plus long du monde : la Barkley Marathons, 160 km sans GPS.",
  "Le coeur d'un coureur bat en moyenne 2.5 milliards de fois dans sa vie.",
  "Courir 1 km brule environ 1 kcal par kg de poids corporel.",
  "Le marathon etait autrefois de 40 km. Les 2.195 km supplementaires viennent des JO de Londres 1908.",
  "Eliud Kipchoge a couru un marathon en moins de 2h (1h59min40s) en 2019.",
  "Les chaussures de course modernes contiennent plus de technologie qu'un satellite des annees 60.",
  "Le parkrun le plus rapide du monde : 13min48s sur 5 km.",
  "Un coureur amateur parcourt en moyenne 1 500 km par an.",
  "La UTMB fait 171 km avec 10 000 m de denivele positif autour du Mont-Blanc.",
  "Le record du Tour de France : 3 404 km en 21 jours par Tadej Pogačar en 2024.",
  "Un cycliste professionnel peut produire 400 watts pendant une heure.",
  "Michael Phelps a remporte 23 medailles d'or olympiques, un record absolu.",
  "Le record du monde du 100m nage libre : 46.80s par Cesar Cielo.",
  "L'Ironman le plus mythique se deroule a Kona (Hawai) : 3.8 km natation, 180 km velo, 42 km course.",
  "Jan Frodeno detient le record de l'Ironman en 7h35min39s.",
  "Les premiers Jeux Olympiques modernes ont eu lieu a Athenes en 1896.",
  "Le saut en hauteur record est de 2.45m par Javier Sotomayor depuis 1993.",
  "Un coureur de 800m atteint 97% de sa VO2 max pendant la course.",
  "Le record du monde du 10 000m : 26min11s par Joshua Cheptegei.",
  "Kilian Jornet a couru l'Everest en montee en 26h pour 8 848m de denivele.",
  "Le record de l'heure cycliste : 56.792 km par Filippo Ganna en 2022.",
  "Une chaussure de running perd 50% de son amorti apres 500-800 km.",
  "Le triathlon est entre aux Jeux Olympiques en 2000 a Sydney.",
  "Paula Radcliffe detient le record du marathon feminin en 2h15min25s depuis 2003.",
  "Un coureur elite a une cadence de 180-200 pas par minute.",
  "Le marathon de Boston est la plus ancienne course annuelle (depuis 1897).",
  "Hicham El Guerrouj detient le record du mile en 3min43s13 depuis 1999.",
  "Un ultra-trailer peut perdre jusqu'a 10% de son poids corporel en une course.",
  "Le record du monde du 5000m : 12min35s par Joshua Cheptegei.",
  "Les coureurs kenyans dominent les marathons grace a leur altitude d'entrainement (2 400m).",
  "Le marathon de New York accueille 50 000 coureurs chaque annee.",
  "Un nageur olympique parcourt environ 15 km par jour a l'entrainement.",
  "Le record du monde du 50m nage libre : 20.91s par Cesar Cielo.",
  "La Diagonale des Fous a La Reunion : 163 km et 9 643m de denivele en moins de 24h pour les meilleurs.",
  "Un coureur brule environ 100 calories par kilometre couru.",
  "Le record du monde du 1500m : 3min26s par Hicham El Guerrouj.",
  "Les marathoniens elites ont un taux de graisse corporelle de 5-10%.",
  "Le Paris-Roubaix cycliste compte 54 km de paves sur 257 km au total.",
  "Un triathlète Ironman peut consommer jusqu'a 8 000 calories en une course.",
  "Le record du monde du 400m : 43.03s par Wayde van Niekerk.",
  "La Spartathlon en Grece : 246 km d'Athenes a Sparte en moins de 36h.",
  "Les coureurs professionnels s'entrainent 2 fois par jour, 6-7 jours par semaine.",
  "Le record du monde du 200m : 19.19s par Usain Bolt a Berlin 2009.",
  "Un coureur de trail peut monter jusqu'a 1 000m de denivele par heure.",
  "Le Western States 100 miles existe depuis 1974 et traverse la Sierra Nevada.",
  "Les chaussures a plaque carbone peuvent ameliorer les performances de 4-5%.",
  "Le record du monde du 3000m steeple : 7min53s par Lamecha Girma.",
  "Un marathonien perd environ 3-4 litres d'eau par la transpiration.",
  "Le Marathon des Sables au Maroc : 250 km en autosuffisance dans le desert.",
  "Les coureurs elites ont une frequence cardiaque au repos de 35-45 bpm.",
  "Le record du monde du 100m haies feminin : 12.12s par Tobi Amusan.",
  "La Hardrock 100 dans le Colorado culmine a 4 270m d'altitude.",
  "Un coureur utilise plus de 200 muscles differents pendant la course.",
  "Le record du monde du relais 4x100m : 36.84s par la Jamaique.",
  "L'Ultra-Trail du Mont Fuji fait 168 km avec 8 000m de denivele.",
  "Les coureurs elites ont une VO2 max superieure a 70 ml/kg/min.",
  "Le record du monde du 400m haies : 45.94s par Karsten Warholm.",
  "La Tor des Geants en Italie : 330 km et 24 000m de denivele non-stop.",
  "Un coureur fait environ 1 200 foulees par kilometre.",
  "Le record du monde du decathlon : 9 126 points par Kevin Mayer.",
  "Les chaussures minimalistes favorisent une attaque avant-pied naturelle.",
];

export function getFactForMilestone(percent: number): string | null {
  const milestoneIndex = Math.floor(percent / 10) - 1;
  if (milestoneIndex >= 0 && milestoneIndex < runnerFacts.length) {
    return runnerFacts[milestoneIndex];
  }
  return null;
}
