export const runnerFacts = [
  "Le record du monde du marathon : 2h00min35s par Kelvin Kiptum !",
  "Usain Bolt atteignait 44.72 km/h en pointe sur 100m.",
  "Un marathonien élite fait environ 43 000 pas pendant une course.",
  "Le trail le plus long du monde : la Barkley Marathons, 160 km sans GPS.",
  "Le cœur d'un sportif bat en moyenne 2.5 milliards de fois dans sa vie.",
  "Courir 1 km brûle environ 1 kcal par kg de poids corporel.",
  "Le marathon était autrefois de 40 km. Les 2.195 km supplémentaires viennent des JO de Londres 1908.",
  "Eliud Kipchoge a couru un marathon en moins de 2h (1h59min40s) en 2019.",
  "Les chaussures de course modernes contiennent plus de technologie qu'un satellite des années 60.",
  "Le parkrun le plus rapide du monde : 13min48s sur 5 km.",
  "Un sportif amateur parcourt en moyenne 1 500 km par an.",
  "La UTMB fait 171 km avec 10 000 m de dénivelé positif autour du Mont-Blanc.",
  "Le record du Tour de France : 3 404 km en 21 jours par Tadej Pogačar en 2024.",
  "Un cycliste professionnel peut produire 400 watts pendant une heure.",
  "Michael Phelps a remporté 23 médailles d'or olympiques, un record absolu.",
  "Le record du monde du 100m nage libre : 46.80s par César Cielo.",
  "L'Ironman le plus mythique se déroule à Kona (Hawaï) : 3.8 km natation, 180 km vélo, 42 km course.",
  "Jan Frodeno détient le record de l'Ironman en 7h35min39s.",
  "Les premiers Jeux Olympiques modernes ont eu lieu à Athènes en 1896.",
  "Le saut en hauteur record est de 2.45m par Javier Sotomayor depuis 1993.",
  "Un sportif de 800m atteint 97% de sa VO2 max pendant la course.",
  "Le record du monde du 10 000m : 26min11s par Joshua Cheptegei.",
  "Kilian Jornet a couru l'Everest en montée en 26h pour 8 848m de dénivelé.",
  "Le record de l'heure cycliste : 56.792 km par Filippo Ganna en 2022.",
  "Une chaussure de running perd 50% de son amorti après 500-800 km.",
  "Le triathlon est entré aux Jeux Olympiques en 2000 à Sydney.",
  "Paula Radcliffe détient le record du marathon féminin en 2h15min25s depuis 2003.",
  "Un sportif élite a une cadence de 180-200 pas par minute.",
  "Le marathon de Boston est la plus ancienne course annuelle (depuis 1897).",
  "Hicham El Guerrouj détient le record du mile en 3min43s13 depuis 1999.",
  "Un ultra-trailer peut perdre jusqu'à 10% de son poids corporel en une course.",
  "Le record du monde du 5000m : 12min35s par Joshua Cheptegei.",
  "Les sportifs kenyans dominent les marathons grâce à leur altitude d'entraînement (2 400m).",
  "Le marathon de New York accueille 50 000 sportifs chaque année.",
  "Un nageur olympique parcourt environ 15 km par jour à l'entraînement.",
  "Le record du monde du 50m nage libre : 20.91s par César Cielo.",
  "La Diagonale des Fous à La Réunion : 163 km et 9 643m de dénivelé en moins de 24h pour les meilleurs.",
  "Un sportif brûle environ 100 calories par kilomètre couru.",
  "Le record du monde du 1500m : 3min26s par Hicham El Guerrouj.",
  "Les marathoniens élites ont un taux de graisse corporelle de 5-10%.",
  "Le Paris-Roubaix cycliste compte 54 km de pavés sur 257 km au total.",
  "Un triathlète Ironman peut consommer jusqu'à 8 000 calories en une course.",
  "Le record du monde du 400m : 43.03s par Wayde van Niekerk.",
  "La Spartathlon en Grèce : 246 km d'Athènes à Sparte en moins de 36h.",
  "Les sportifs professionnels s'entraînent 2 fois par jour, 6-7 jours par semaine.",
  "Le record du monde du 200m : 19.19s par Usain Bolt à Berlin 2009.",
  "Un sportif de trail peut monter jusqu'à 1 000m de dénivelé par heure.",
  "Le Western States 100 miles existe depuis 1974 et traverse la Sierra Nevada.",
  "Les chaussures à plaque carbone peuvent améliorer les performances de 4-5%.",
  "Le record du monde du 3000m steeple : 7min53s par Lamecha Girma.",
  "Un marathonien perd environ 3-4 litres d'eau par la transpiration.",
  "Le Marathon des Sables au Maroc : 250 km en autosuffisance dans le désert.",
  "Les sportifs élites ont une fréquence cardiaque au repos de 35-45 bpm.",
  "Le record du monde du 100m haies féminin : 12.12s par Tobi Amusan.",
  "La Hardrock 100 dans le Colorado culmine à 4 270m d'altitude.",
  "Un sportif utilise plus de 200 muscles différents pendant la course.",
  "Le record du monde du relais 4x100m : 36.84s par la Jamaïque.",
  "L'Ultra-Trail du Mont Fuji fait 168 km avec 8 000m de dénivelé.",
  "Les sportifs élites ont une VO2 max supérieure à 70 ml/kg/min.",
  "Le record du monde du 400m haies : 45.94s par Karsten Warholm.",
  "La Tor des Géants en Italie : 330 km et 24 000m de dénivelé non-stop.",
  "Un sportif fait environ 1 200 foulées par kilomètre.",
  "Le record du monde du décathlon : 9 126 points par Kevin Mayer.",
  "Les chaussures minimalistes favorisent une attaque avant-pied naturelle.",
];

export function getFactForMilestone(percent: number): string | null {
  const milestoneIndex = Math.floor(percent / 10) - 1;
  if (milestoneIndex >= 0 && milestoneIndex < runnerFacts.length) {
    return runnerFacts[milestoneIndex];
  }
  return null;
}
